apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: test
  namespace: test
spec:
#Cron Time is set according to server time, ensure server time zone and set accordingly.
  schedule:  "*/5 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccount: postgress-backup-cronjob-test  ### service account created
          serviceAccountName: postgress-backup-cronjob-test   #### 
          containers:
          - name: test
            image: speedyrogue007/postgresbackup:latest   #### chnage image name to ecr
            imagePullPolicy: Always
            envFrom:
              - secretRef:
                  name: postgresql-cron-secret-test  #### get its env from secret file thats base 64 encoded
            args:
            - /bin/bash
            - -c
            - cd /home/root; ls; bash postgres-backup.sh;
          restartPolicy: OnFailure

      backoffLimit: 1