apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: 'arn:aws:iam::132311061266:role/test-cronjob' ### change the name to the role
  name: postgress-backup-cronjob-test